import { getOpenAIClient, OPENAI_MODEL } from "@/lib/openai-client";
import type {
  AtRiskRow,
  LatenessPatternRow,
  ReliabilityRow,
} from "@/lib/ai-analysis-mock";
import type { SignalTypeRow } from "@/lib/people-mock";

/**
 * AI narrative layer for the Insights page.
 *
 * The underlying numbers (lateness counts, risk scores, trends) stay
 * rule-based — see ai-analysis-mock.ts — but the written executive
 * summary is generated by OpenAI from those numbers when OPENAI_API_KEY
 * is configured. Falls back to a static line if the key is missing or
 * the request fails, so the page never breaks on API issues.
 */

export type InsightsNarrativeInput = {
  lateness: LatenessPatternRow[];
  causes: SignalTypeRow[];
  atRisk: AtRiskRow[];
  ranking: ReliabilityRow[];
};

export type InsightsNarrative = {
  text: string;
  source: "openai" | "fallback";
};

const FALLBACK_TEXT =
  "AI-written summary unavailable right now — showing rule-based analysis only below. Configure OPENAI_API_KEY in .env to enable AI-generated summaries.";

function buildPrompt(input: InsightsNarrativeInput): string {
  const latenessLines =
    input.lateness
      .map((row) => `- ${row.person.name}: ${row.lateCount} late arrivals`)
      .join("\n") || "- none flagged";

  const causeLines =
    input.causes
      .map((row) => `- ${row.type}: ${row.count}`)
      .join("\n") || "- none recorded";

  const atRiskLines =
    input.atRisk
      .map(
        (row) =>
          `- ${row.person.name}: reliability ${row.reliabilityScore}/100 — ${row.reason}`,
      )
      .join("\n") || "- none flagged";

  const rankingLines =
    input.ranking
      .slice(0, 5)
      .map((row) => `- ${row.person.name}: ${row.score}/100, trend ${row.trend}`)
      .join("\n") || "- no data";

  return [
    "Frequent lateness patterns (last 30 days):",
    latenessLines,
    "",
    "Common causes of attendance issues:",
    causeLines,
    "",
    "Employees at risk:",
    atRiskLines,
    "",
    "Top reliability scores (highest 5):",
    rankingLines,
  ].join("\n");
}

export async function generateInsightsNarrative(
  input: InsightsNarrativeInput,
): Promise<InsightsNarrative> {
  const client = getOpenAIClient();
  if (!client) {
    return { text: FALLBACK_TEXT, source: "fallback" };
  }

  try {
    const completion = await client.chat.completions.create({
      model: OPENAI_MODEL,
      temperature: 0.4,
      max_tokens: 220,
      messages: [
        {
          role: "system",
          content:
            "You are an attendance operations analyst writing for a manager dashboard. " +
            "Write a concise 3-5 sentence executive summary of the attendance signals given. " +
            "Only use the numbers provided — never invent data. Professional, direct tone.",
        },
        { role: "user", content: buildPrompt(input) },
      ],
    });

    const text = completion.choices[0]?.message?.content?.trim();
    if (!text) {
      return { text: FALLBACK_TEXT, source: "fallback" };
    }
    return { text, source: "openai" };
  } catch (error) {
    console.error("[ai-narrative] OpenAI request failed:", error);
    return { text: FALLBACK_TEXT, source: "fallback" };
  }
}
