import PDFDocument from "pdfkit";
import { generateInsightsNarrative, type InsightsNarrative } from "@/lib/ai-narrative";
import { RISK_LABELS } from "@/lib/dashboard-mock";
import { TREND_LABELS } from "@/lib/ai-analysis-mock";
import {
  employeesAtRisk,
  frequentLatenessPatterns,
  reliabilityRanking,
  signalTypeBreakdown,
} from "@/lib/insights-queries";

/**
 * Renders the same data /insights shows (src/lib/insights-queries.ts +
 * the AI summary from src/lib/ai-narrative.ts) as a downloadable PDF —
 * the "Build report" button next to the time-window switcher hits
 * src/app/api/insights/report/route.ts, which calls this.
 *
 * pdfkit is pure JS (no native binaries / headless browser), so this
 * runs fine in a normal Node.js route handler — no extra
 * infrastructure. Uses pdfkit's built-in Helvetica/Helvetica-Bold, so
 * no font files need to be bundled either.
 *
 * `narrativeOverride` lets the caller embed a summary the manager has
 * already reviewed/refined on the page (see
 * src/app/insights/report/report-builder.tsx +
 * src/app/api/insights/summary/refine/route.ts) instead of
 * re-fetching the cached per-window default.
 */
export async function generateInsightsReportPdf(
  days: number,
  narrativeOverride?: InsightsNarrative,
): Promise<Buffer> {
  const [narrative, lateness, causes, atRisk, ranking] = await Promise.all([
    narrativeOverride ?? generateInsightsNarrative(days),
    frequentLatenessPatterns(days, 3),
    signalTypeBreakdown(days),
    employeesAtRisk(days),
    reliabilityRanking(days, 10),
  ]);

  const doc = new PDFDocument({ size: "LETTER", margin: 50 });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk) => chunks.push(chunk as Buffer));
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const generatedAt = new Date().toLocaleString("en-US", {
    dateStyle: "long",
    timeStyle: "short",
  });

  // -- Header --------------------------------------------------------
  doc.font("Helvetica-Bold").fontSize(20).text("AI Attendance Analysis");
  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor("#555")
    .text(`Last ${days} days · generated ${generatedAt}`);
  doc.fillColor("#000").moveDown(1.2);

  // -- AI summary ------------------------------------------------------
  sectionHeading(
    doc,
    "AI Summary",
    narrative.source === "openai" ? "Generated by OpenAI" : "Fallback",
  );
  doc.font("Helvetica").fontSize(11).text(narrative.text, { align: "left" });
  doc.moveDown(1.2);

  // -- Frequent lateness patterns --------------------------------------
  sectionHeading(doc, "Frequent Lateness Patterns", `3+ late arrivals · last ${days} days`);
  if (lateness.length === 0) {
    emptyState(doc, "No employee has crossed the frequent-lateness threshold this cycle.");
  } else {
    for (const row of lateness) {
      bulletLine(doc, row.name, row.narrative);
    }
  }
  doc.moveDown(1.2);

  // -- Common causes -----------------------------------------------------
  sectionHeading(doc, "Common Causes of Attendance Issues");
  if (causes.length === 0) {
    emptyState(doc, "No signals recorded in this window.");
  } else {
    for (const row of causes) {
      bulletLine(doc, row.type, `${row.count} occurrence${row.count === 1 ? "" : "s"}`);
    }
  }
  doc.moveDown(1.2);

  // -- Employees at risk -------------------------------------------------
  sectionHeading(doc, "Employees at Risk", `${atRisk.length} flagged`);
  if (atRisk.length === 0) {
    emptyState(doc, "No employees flagged as at risk right now.");
  } else {
    for (const row of atRisk) {
      bulletLine(
        doc,
        `${row.name}${row.isTerminationFlag ? " (Termination threshold)" : ""}`,
        `${row.points} pts · ${RISK_LABELS[row.riskLevel]} — ${row.reason}`,
      );
    }
  }
  doc.moveDown(1.2);

  // -- Reliability ranking ------------------------------------------------
  sectionHeading(doc, "Attendance Points & Improvement Trends", `Top ${ranking.length} · vs. prior ${days} days`);
  if (ranking.length === 0) {
    emptyState(doc, "No ranking data available for this window.");
  } else {
    reliabilityTable(doc, ranking);
  }

  doc
    .fontSize(8)
    .fillColor("#888")
    .text(
      "Live query · reads from Neon (schema in docs/database/database.md) · SMS intake not connected",
      50,
      doc.page.height - 40,
      { align: "left" },
    );

  doc.end();
  return done;
}

function sectionHeading(
  doc: PDFKit.PDFDocument,
  title: string,
  caption?: string,
): void {
  const y = doc.y;
  doc.font("Helvetica-Bold").fontSize(13).fillColor("#000").text(title, { continued: false });
  if (caption) {
    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#666")
      .text(caption, doc.page.margins.left, y, {
        align: "right",
        width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
      });
  }
  doc.fillColor("#000").moveDown(0.5);
}

function bulletLine(doc: PDFKit.PDFDocument, title: string, detail: string): void {
  doc.font("Helvetica-Bold").fontSize(10.5).text(`•  ${title}`, { continued: false });
  doc
    .font("Helvetica")
    .fontSize(9.5)
    .fillColor("#444")
    .text(detail, { indent: 14 });
  doc.fillColor("#000").moveDown(0.35);
}

function emptyState(doc: PDFKit.PDFDocument, text: string): void {
  doc.font("Helvetica-Oblique").fontSize(9.5).fillColor("#666").text(text);
  doc.fillColor("#000");
}

function reliabilityTable(
  doc: PDFKit.PDFDocument,
  ranking: Awaited<ReturnType<typeof reliabilityRanking>>,
): void {
  const startX = doc.page.margins.left;
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const colEmployee = width * 0.45;
  const colPoints = width * 0.3;
  const colTrend = width * 0.25;

  doc.font("Helvetica-Bold").fontSize(9.5);
  const headerY = doc.y;
  doc.text("Employee", startX, headerY, { width: colEmployee });
  doc.text("Points · Status", startX + colEmployee, headerY, {
    width: colPoints,
    align: "right",
  });
  doc.text("Trend", startX + colEmployee + colPoints, headerY, {
    width: colTrend,
    align: "right",
  });
  doc.moveDown(0.3);
  doc
    .moveTo(startX, doc.y)
    .lineTo(startX + width, doc.y)
    .strokeColor("#ccc")
    .stroke();
  doc.moveDown(0.3);

  doc.font("Helvetica").fontSize(9.5);
  for (const row of ranking) {
    const rowY = doc.y;
    doc.text(row.name, startX, rowY, { width: colEmployee });
    doc.text(`${row.points} pts · ${RISK_LABELS[row.riskLevel]}`, startX + colEmployee, rowY, {
      width: colPoints,
      align: "right",
    });
    doc.text(TREND_LABELS[row.trend], startX + colEmployee + colPoints, rowY, {
      width: colTrend,
      align: "right",
    });
    doc.moveDown(0.4);
  }
}
