/**
 * The 7/30/90-day time windows the Insights page (and its PDF report,
 * generated by src/lib/insights-report.ts) let the user pick between.
 * Shared here so /insights and /api/insights/report validate and
 * default the `?days=` param identically.
 */
export const DAY_WINDOWS = [7, 30, 90] as const;
export const DEFAULT_DAYS = 30;

export function parseDays(raw: string | null | undefined): number {
  const parsed = Number(raw);
  return DAY_WINDOWS.includes(parsed as (typeof DAY_WINDOWS)[number])
    ? parsed
    : DEFAULT_DAYS;
}
