import { generateInsightsNarrative } from "@/lib/ai-narrative";

/**
 * Isolated async server component for the AI summary section. Kept
 * separate from InsightsPage so it can be wrapped in its own
 * <Suspense> boundary — the OpenAI round-trip (cached, but still a
 * network call on a cache miss) no longer blocks the deterministic
 * sections below it from rendering.
 */
export async function AiSummaryCard({ days }: { days: number }) {
  const narrative = await generateInsightsNarrative(days);

  return (
    <section
      className="animate-fade-up-delay-1 mt-8"
      aria-labelledby="ai-summary-heading"
    >
      <div className="mb-3 flex items-baseline justify-between gap-3">
        <h2
          id="ai-summary-heading"
          className="font-display text-lg font-semibold tracking-tight text-ink"
        >
          AI summary
        </h2>
        <p className="text-sm tracking-wide text-slate/55 uppercase">
          {narrative.source === "openai" ? "Generated by OpenAI" : "Fallback"}
        </p>
      </div>
      <div className="border border-line bg-white/65 px-5 py-4">
        <p className="text-sm leading-relaxed text-slate/80">
          {narrative.text}
        </p>
      </div>
    </section>
  );
}

/** Skeleton shown while AiSummaryCard streams in. */
export function AiSummaryCardSkeleton() {
  return (
    <section className="mt-8" aria-hidden>
      <div className="mb-3 flex items-baseline justify-between gap-3">
        <div className="h-5 w-24 animate-pulse bg-surface-2" />
        <div className="h-4 w-32 animate-pulse bg-surface-2" />
      </div>
      <div className="border border-line bg-white/65 px-5 py-4">
        <div className="h-3.5 w-full animate-pulse bg-surface-2" />
        <div className="mt-2 h-3.5 w-11/12 animate-pulse bg-surface-2" />
        <div className="mt-2 h-3.5 w-3/4 animate-pulse bg-surface-2" />
      </div>
    </section>
  );
}
